name: Build and deploy Node.js app to Azure Web App - MernStack

on:
  push:
    branches:
      - master   # IMPORTANT: match your branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MernStack'
          package: ./server
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_41C2DAB4E9A24496999E5EA7BBF597D2 }}